monitor = eDP-1, 1920x1080, 0x0, 1
monitor = DP-2, 2560x1440@165,0x0,1

exec-once = ~/.config/waybar/launch.sh

device {
    # name = epic-mouse-v1
    # sensitivity = -0.5
    name = razer-razer-basilisk-ultimate-dongle
    sensitivity = -1
    accel_profile = custom 3 0 1
}
